features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://tthzlogorechthoekstroke5px_0.png'
favicon:
  use_default: 0
  path: 'public://vlagje.png'
  mimetype: image/png
d8w3css_font_awesome_4: 0
d8w3css_google_font: 0
website_width: w3-width-100-percent
full_opacity_onscroll: 0
equal_width: 0
current_theme: w3-theme-00012
color_page_wrapper: ''
color_header: w3-light-green
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: ''
color_top_container: w3-light-green
color_top_first: ''
color_top_second: ''
color_top_third: ''
color_page_title: ''
color_main: ''
color_breadcrumb: ''
color_sidebar_first: ''
color_content: ''
color_sidebar_second: ''
color_bottom_container: ''
color_bottom_first: ''
color_bottom_second: ''
color_bottom_third: ''
color_bottom_forth: ''
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: 'w3-light-green w3-link-bg-white'
color_copyright: w3-link-light-grey
show_social_icon: 1
facebook_url: 'https://www.facebook.com/people/TTHZ-Cycling-Team/100054480699308/'
twitter_url: ''
pinterest_url: ''
google_plus_url: ''
linkedin_url: ''
instagram_url: 'https://www.instagram.com/tthz_cycling_team/'
youtube_url: ''
drupal_url: ''
rss_url: ''
copyright_text: 'Â© TTHZ CYCLING TEAM 2025 | Privacy settings'
show_credit_link: 0
layout_user_login_custom: 1
breadcrumb_page_title: 0
border_animation: 1
d8w3css_font_awesome: '4'
d8w3css_google_font_local: 1
d8w3css_site_gf: none
d8w3css_site_gfh: none
d8w3css_site_gfs: none
sitename_animation: none
pagetitle_animation: none
mastodon_url: ''
