#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    backuptthz10-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "backuptthz10-redirectHttps"
    backuptthz10-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "backuptthz10-redirectHttps"
    backuptthz10-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "backuptthz10-redirectHttps"
    backuptthz10-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "backuptthz10-redirectHttps"
    
    
    backuptthz10-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    backuptthz10-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-web-80"
      ruleSyntax: v3
      
      tls: true
      
    backuptthz10-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    backuptthz10-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^backuptthz10\.ddev\.site$`)
      
      service: "backuptthz10-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    backuptthz10-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    backuptthz10-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-backuptthz10-phpmyadmin:80
        
    
    backuptthz10-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-backuptthz10-web:80
        
    backuptthz10-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-backuptthz10-web:8025
        
    
    
    backuptthz10-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-backuptthz10-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/backuptthz10.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/backuptthz10.key