settings:
  allowed_values:
    -
      label: 'Displays content at the top left corner of the w3-display-container'
    -
      label: 'Displays content at the top right corner of the w3-display-container'
    -
      label: 'Displays content at the bottom left corner of the w3-display-container'
    -
      label: 'Displays content at the bottom right corner of the w3-display-container'
    -
      label: 'Displays content to the left (middle left) of the w3-display-container'
    -
      label: 'Displays content to the right (middle right) of the w3-display-container'
    -
      label: 'Displays content in the middle (center) of the w3-display-container'
    -
      label: 'Displays content at the top middle of the w3-display-container'
    -
      label: 'Displays content at the bottom middle of the w3-display-container'
