_core:
  default_config_hash: WO58HtU_-1NeW5R87sQNWSLqyknLYVLFu1cT7KuHRx4
langcode: nl
enabled: true
site_key: ''
secret_key: ''
element_defaults:
  action: default
  threshold: '0.5'
  verify_hostname: false
  error_message: 'Antibot verification failed, please try again.'
log_successes: false
