_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
langcode: nl
enabled_default: 0
default_challenge: captcha/Math
description: 'Deze vraag is om te controleren dat u een mens bent, om geautomatiseerde invoer (spam) te voorkomen.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: false
wrong_captcha_response_message: 'Uw CAPTCHA-antwoord was niet juist.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
