_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: nl
module:
  aggregator: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  consumers: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_entity_mask: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gatsby_extras: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_tabs: 0
  jquery_ui_tooltip: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_json_example: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  recaptcha_v3: 0
  redirect: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_gmap: 0
  simple_oauth: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_demo_event_registration: 0
  webform_node: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  ds: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  gatsby: 100
  gatsby_instantpreview: 100
  gatsby_fastbuilds: 101
  standard: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  drupal8_w3css_theme: 0
  tthz9: 0
  zinble: 0
profile: standard
