_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
langcode: nl
definitions:
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
