features:
  name: 1
  slogan: 1
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 0
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
