features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_0.png'
favicon:
  use_default: 1
website_width: ''
top_region: 0
main_region: 0
bottom_region: 1
footer_region: 1
equal_width: 0
current_theme: w3-theme-blue-grey
color_page_wrapper: ''
color_header: ''
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: ''
color_top_container: w3-box-shadow-0
color_top_first: ''
color_top_second: w3-box-shadow-0
color_top_third: ''
color_page_title: ''
color_main: ''
color_breadcrumb: ''
color_sidebar_first: 'w3-box-shadow-0 '
color_content: 'w3-box-shadow-0 '
color_sidebar_second: 'w3-box-shadow-0 '
color_bottom_container: ''
color_bottom_first: ''
color_bottom_second: ''
color_bottom_third: ''
color_bottom_forth: ''
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: ''
color_copyright: ''
show_social_icon: 0
facebook_url: 'https://www.facebook.com/search/top?q=tthz%20cycling%20team'
twitter_url: ''
pinterest_url: ''
google_plus_url: ''
linkedin_url: ''
instagram_url: ''
youtube_url: ''
drupal_url: ''
rss_url: ''
copyright_text: 'Â© TTHZ CYCLING TEAM 2022'
show_credit_link: 0
d8w3css_font_awesome_4: 0
d8w3css_google_font: 0
full_opacity_onscroll: 1
