_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
langcode: nl
enable_globally: 0
enable_globally_on_admin_routes: false
default_challenge: recaptcha_v3/recaptchav3
description: ''
title: CAPTCHA
administration_mode: true
administration_mode_on_admin_routes: false
whitelist_ips: ''
wrong_captcha_response_message: 'Uw CAPTCHA-antwoord was niet juist.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
